nama=("M.RIFKY ANSHORY")
nim=("TI20230027")
semester=("2(dua)")
status=("Pelajar (Mahasiswa)")
agama=("ISLAM")
lahir=("PRAYA,03 JANURAI 2005")
usia=int(19)
kelamin=("LAKI - LAKI")
alamat=("KAMPUNG MISPALAH TIMUR kec.praya tengah")
email=("rifkyanshori8@gmail.com")
wa=("+6287769430193")
fb=("Rifky Anshory")
ig=("mrifky_anshory")
tiktok=("rifkyanshory5")
mi=("MI MADRASAH IBTIDAIYAH NW MISPALAH PRAYA")
mts=("MTs ISLAHUL IKHWAN NW MISPALAH PRAYA")
ma=("MA  DARUL AMININ NW AIK MUAL PRAYA")
kuliah=("SEKOLAH TINGGI MANAJEMEN INFORMASI DAN KOMUNIKASI LOMBOK")
pengalaman1=("PERNAH IKUT MAIN KARATE DI BKKBN DI BELAKANG KANTOR BUPATI YG DULU (SABUK HIJAU)")
pengalaman2=("PERNAH IKUT MAIN BADMINTHON DI DI KONI MJ(MUHAJIRIN)(NBC)PRAYA LOMBOK")  
pengalaman3=("PERNAH IKUT TANDINGAN AA BOXER DI TIMUK LEKONG PRAYA LOMBOK")
keahlian=("Publik Spiking lumayan bagus")


print("--------------------------------------")
print("         CURRICULUM VITAE             ")
print("by : M.Rifky anshory")
print("--------------------------------------")
print("")
print("DATA PRIBADI")
print("--------------------------------------")
print("|    Nama                   | ",nama)
print("|    Status                 | ",status)
print("|    NIM                    | ",nim)
print("|    Semester               | ",semester)
print("|    Jenis Kelamin          | ",kelamin)
print("|    Agama                  | ",agama)
print("|    Tempat & Tanggal Lahir | ",lahir)
print("|    Umur                   | ",usia,"Tahun")
print("|    Alamat                 | ",alamat)
print("--------------------------------------")
print("")
print("PENDIDIKAN")
print("----------------------------------------------")
print("MADRASAH IBTIDAIYAH                   | ",mi)
print("MADRASAH TERASNAWIYAH                  | ",mts)
print("MADRASAH ALIYAH                        | ",ma)
print("PERGURUAN TINGGI                       | ",kuliah)
print("----------------------------------------------")
print("")
print("MEDIA SOSIAL")
print("--------------------------------------")
print("|    NOMOR HP/WA | ",wa)
print("|    INSTAGRAM   | ",ig)
print("|    FACEBOOK    | ",fb)
print("|    TIKTOK      | ",tiktok)
print("|    E_mail      | ",email)
print("--------------------------------------")
print("")
print("PENGALAMAN")
print("--------------------------------------")
print("- ",pengalaman1)
print("- ",pengalaman2)
print("- ",pengalaman3)
print("--------------------------------------")
print("")
print("KEAHLIAN")
print("--------------------------------------")
print("- ",keahlian)
print("--------------------------------------")
print("            TERIMA KASIH              ")
print("--------------------------------------")
